/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShipmentDetails = IDL.Record({
  'weight' : IDL.Float64,
  'description' : IDL.Text,
  'deliveryType' : IDL.Variant({
    'express' : IDL.Null,
    'priority' : IDL.Null,
    'standard' : IDL.Null,
  }),
  'quantity' : IDL.Nat,
  'category' : IDL.Variant({
    'cargo' : IDL.Null,
    'freight' : IDL.Null,
    'document' : IDL.Null,
    'parcel' : IDL.Null,
  }),
});
export const Address = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ShippingOrder = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'in_transit' : IDL.Null,
    'delivered' : IDL.Null,
  }),
  'owner' : IDL.Principal,
  'shipment' : ShipmentDetails,
  'sender' : Address,
  'receiver' : Address,
});
export const UserProfile = IDL.Record({
  'country' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createShippingOrder' : IDL.Func([ShippingOrder], [], []),
  'getAllShippingOrders' : IDL.Func([], [IDL.Vec(ShippingOrder)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyShippingOrders' : IDL.Func([], [IDL.Vec(ShippingOrder)], ['query']),
  'getShippingOrder' : IDL.Func([IDL.Text], [ShippingOrder], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'cancelled' : IDL.Null,
          'pending' : IDL.Null,
          'in_transit' : IDL.Null,
          'delivered' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShipmentDetails = IDL.Record({
    'weight' : IDL.Float64,
    'description' : IDL.Text,
    'deliveryType' : IDL.Variant({
      'express' : IDL.Null,
      'priority' : IDL.Null,
      'standard' : IDL.Null,
    }),
    'quantity' : IDL.Nat,
    'category' : IDL.Variant({
      'cargo' : IDL.Null,
      'freight' : IDL.Null,
      'document' : IDL.Null,
      'parcel' : IDL.Null,
    }),
  });
  const Address = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ShippingOrder = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'in_transit' : IDL.Null,
      'delivered' : IDL.Null,
    }),
    'owner' : IDL.Principal,
    'shipment' : ShipmentDetails,
    'sender' : Address,
    'receiver' : Address,
  });
  const UserProfile = IDL.Record({
    'country' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createShippingOrder' : IDL.Func([ShippingOrder], [], []),
    'getAllShippingOrders' : IDL.Func([], [IDL.Vec(ShippingOrder)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyShippingOrders' : IDL.Func([], [IDL.Vec(ShippingOrder)], ['query']),
    'getShippingOrder' : IDL.Func([IDL.Text], [ShippingOrder], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'cancelled' : IDL.Null,
            'pending' : IDL.Null,
            'in_transit' : IDL.Null,
            'delivered' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };