/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShipmentDetails {
    weight: number;
    description: string;
    deliveryType: Variant_express_priority_standard;
    quantity: bigint;
    category: Variant_cargo_freight_document_parcel;
}
export interface ShippingOrder {
    id: string;
    status: Variant_cancelled_pending_in_transit_delivered;
    owner: Principal;
    shipment: ShipmentDetails;
    sender: Address;
    receiver: Address;
}
export interface UserProfile {
    country: string;
    name: string;
    email: string;
    passwordHash: string;
    phone: string;
}
export interface Address {
    country: string;
    city: string;
    name: string;
    email?: string;
    address: string;
    phone: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cancelled_pending_in_transit_delivered {
    cancelled = "cancelled",
    pending = "pending",
    in_transit = "in_transit",
    delivered = "delivered"
}
export enum Variant_cargo_freight_document_parcel {
    cargo = "cargo",
    freight = "freight",
    document_ = "document",
    parcel = "parcel"
}
export enum Variant_express_priority_standard {
    express = "express",
    priority = "priority",
    standard = "standard"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createShippingOrder(order: ShippingOrder): Promise<void>;
    getAllShippingOrders(): Promise<Array<ShippingOrder>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyShippingOrders(): Promise<Array<ShippingOrder>>;
    getShippingOrder(orderId: string): Promise<ShippingOrder>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerUser(profile: UserProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateOrderStatus(orderId: string, status: Variant_cancelled_pending_in_transit_delivered): Promise<void>;
}
import type { Address as _Address, ShipmentDetails as _ShipmentDetails, ShippingOrder as _ShippingOrder, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createShippingOrder(arg0: ShippingOrder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createShippingOrder(to_candid_ShippingOrder_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShippingOrder(to_candid_ShippingOrder_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllShippingOrders(): Promise<Array<ShippingOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShippingOrders();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShippingOrders();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyShippingOrders(): Promise<Array<ShippingOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyShippingOrders();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyShippingOrders();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShippingOrder(arg0: string): Promise<ShippingOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.getShippingOrder(arg0);
                return from_candid_ShippingOrder_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShippingOrder(arg0);
            return from_candid_ShippingOrder_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerUser(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: Variant_cancelled_pending_in_transit_delivered): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_variant_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Address_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Address): Address {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ShipmentDetails_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShipmentDetails): ShipmentDetails {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_ShippingOrder_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShippingOrder): ShippingOrder {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        in_transit: null;
    } | {
        delivered: null;
    };
    owner: Principal;
    shipment: _ShipmentDetails;
    sender: _Address;
    receiver: _Address;
}): {
    id: string;
    status: Variant_cancelled_pending_in_transit_delivered;
    owner: Principal;
    shipment: ShipmentDetails;
    sender: Address;
    receiver: Address;
} {
    return {
        id: value.id,
        status: from_candid_variant_n15(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        shipment: from_candid_ShipmentDetails_n16(_uploadFile, _downloadFile, value.shipment),
        sender: from_candid_Address_n20(_uploadFile, _downloadFile, value.sender),
        receiver: from_candid_Address_n20(_uploadFile, _downloadFile, value.receiver)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: number;
    description: string;
    deliveryType: {
        express: null;
    } | {
        priority: null;
    } | {
        standard: null;
    };
    quantity: bigint;
    category: {
        cargo: null;
    } | {
        freight: null;
    } | {
        document: null;
    } | {
        parcel: null;
    };
}): {
    weight: number;
    description: string;
    deliveryType: Variant_express_priority_standard;
    quantity: bigint;
    category: Variant_cargo_freight_document_parcel;
} {
    return {
        weight: value.weight,
        description: value.description,
        deliveryType: from_candid_variant_n18(_uploadFile, _downloadFile, value.deliveryType),
        quantity: value.quantity,
        category: from_candid_variant_n19(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    city: string;
    name: string;
    email: [] | [string];
    address: string;
    phone: string;
}): {
    country: string;
    city: string;
    name: string;
    email?: string;
    address: string;
    phone: string;
} {
    return {
        country: value.country,
        city: value.city,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.email)),
        address: value.address,
        phone: value.phone
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    in_transit: null;
} | {
    delivered: null;
}): Variant_cancelled_pending_in_transit_delivered {
    return "cancelled" in value ? Variant_cancelled_pending_in_transit_delivered.cancelled : "pending" in value ? Variant_cancelled_pending_in_transit_delivered.pending : "in_transit" in value ? Variant_cancelled_pending_in_transit_delivered.in_transit : "delivered" in value ? Variant_cancelled_pending_in_transit_delivered.delivered : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    express: null;
} | {
    priority: null;
} | {
    standard: null;
}): Variant_express_priority_standard {
    return "express" in value ? Variant_express_priority_standard.express : "priority" in value ? Variant_express_priority_standard.priority : "standard" in value ? Variant_express_priority_standard.standard : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cargo: null;
} | {
    freight: null;
} | {
    document: null;
} | {
    parcel: null;
}): Variant_cargo_freight_document_parcel {
    return "cargo" in value ? Variant_cargo_freight_document_parcel.cargo : "freight" in value ? Variant_cargo_freight_document_parcel.freight : "document" in value ? Variant_cargo_freight_document_parcel.document : "parcel" in value ? Variant_cargo_freight_document_parcel.parcel : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShippingOrder>): Array<ShippingOrder> {
    return value.map((x)=>from_candid_ShippingOrder_n13(_uploadFile, _downloadFile, x));
}
function to_candid_Address_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Address): _Address {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ShipmentDetails_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentDetails): _ShipmentDetails {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_ShippingOrder_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShippingOrder): _ShippingOrder {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    country: string;
    city: string;
    name: string;
    email?: string;
    address: string;
    phone: string;
}): {
    country: string;
    city: string;
    name: string;
    email: [] | [string];
    address: string;
    phone: string;
} {
    return {
        country: value.country,
        city: value.city,
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        address: value.address,
        phone: value.phone
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_cancelled_pending_in_transit_delivered;
    owner: Principal;
    shipment: ShipmentDetails;
    sender: Address;
    receiver: Address;
}): {
    id: string;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        in_transit: null;
    } | {
        delivered: null;
    };
    owner: Principal;
    shipment: _ShipmentDetails;
    sender: _Address;
    receiver: _Address;
} {
    return {
        id: value.id,
        status: to_candid_variant_n5(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        shipment: to_candid_ShipmentDetails_n6(_uploadFile, _downloadFile, value.shipment),
        sender: to_candid_Address_n10(_uploadFile, _downloadFile, value.sender),
        receiver: to_candid_Address_n10(_uploadFile, _downloadFile, value.receiver)
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: number;
    description: string;
    deliveryType: Variant_express_priority_standard;
    quantity: bigint;
    category: Variant_cargo_freight_document_parcel;
}): {
    weight: number;
    description: string;
    deliveryType: {
        express: null;
    } | {
        priority: null;
    } | {
        standard: null;
    };
    quantity: bigint;
    category: {
        cargo: null;
    } | {
        freight: null;
    } | {
        document: null;
    } | {
        parcel: null;
    };
} {
    return {
        weight: value.weight,
        description: value.description,
        deliveryType: to_candid_variant_n8(_uploadFile, _downloadFile, value.deliveryType),
        quantity: value.quantity,
        category: to_candid_variant_n9(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cancelled_pending_in_transit_delivered): {
    cancelled: null;
} | {
    pending: null;
} | {
    in_transit: null;
} | {
    delivered: null;
} {
    return value == Variant_cancelled_pending_in_transit_delivered.cancelled ? {
        cancelled: null
    } : value == Variant_cancelled_pending_in_transit_delivered.pending ? {
        pending: null
    } : value == Variant_cancelled_pending_in_transit_delivered.in_transit ? {
        in_transit: null
    } : value == Variant_cancelled_pending_in_transit_delivered.delivered ? {
        delivered: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_express_priority_standard): {
    express: null;
} | {
    priority: null;
} | {
    standard: null;
} {
    return value == Variant_express_priority_standard.express ? {
        express: null
    } : value == Variant_express_priority_standard.priority ? {
        priority: null
    } : value == Variant_express_priority_standard.standard ? {
        standard: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cargo_freight_document_parcel): {
    cargo: null;
} | {
    freight: null;
} | {
    document: null;
} | {
    parcel: null;
} {
    return value == Variant_cargo_freight_document_parcel.cargo ? {
        cargo: null
    } : value == Variant_cargo_freight_document_parcel.freight ? {
        freight: null
    } : value == Variant_cargo_freight_document_parcel.document ? {
        document_: null
    } : value == Variant_cargo_freight_document_parcel.parcel ? {
        parcel: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
